language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t wndud0159/react-test-app -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true wndud0159/react-test-app npm run test

after_success:
  - docker build -t wndud0159/docker-frontend ./client
  - docker build -t wndud0159/docker-backend ./server
  - docker build -t wndud0159/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push wndud0159/docker-frontend
  - docker push wndud0159/docker-backend
  - docker push wndud0159/docker-nginx

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-container-app"
  env: "Multicontainerapp-env"
  bucket_name: elasticbeanstalk-us-east-1-276223326741
  bucket_path: "multi-container-app"
  on:
    branch: main
  
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY

